---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/menendes/centralizedConfSpringCloud.git
          #username: abc
          #password: abc
          search-paths:
            - 'station*'
  security:
    user:
      name: zib
      password: zib

